# Generated by Django 4.1.3 on 2022-11-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_categoria_desc_categoria_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidade',
            old_name='unidade_desc',
            new_name='unidade',
        ),
    ]
