# Generated by Django 4.1.3 on 2022-11-17 10:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice_parcela', models.IntegerField()),
                ('vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('compra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcela_pagamento', to='shopping.compra')),
            ],
        ),
    ]
