# Generated by Django 4.2 on 2023-04-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_client', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Juridical',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client.client')),
                ('cnpj', models.CharField(blank=True, max_length=32, null=True)),
                ('fantasy_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Physical',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client.client')),
                ('cpf', models.CharField(blank=True, max_length=32, null=True)),
                ('rg', models.CharField(blank=True, max_length=32, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
