# Generated by Django 4.1.3 on 2022-11-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_pessoa_data_criacao_alter_pessoa_data_edicao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoafisica',
            old_name='pessoa_id',
            new_name='pessoa',
        ),
        migrations.RenameField(
            model_name='pessoajuridica',
            old_name='pessoa_id',
            new_name='pessoa',
        ),
    ]
