# Generated by Django 4.1.3 on 2022-11-18 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria_desc',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='marca_desc',
            new_name='marca',
        ),
    ]
